# Generated by Django 4.1.4 on 2023-01-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_comentario_comentario_alter_post_campo_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='comentario',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='campo_blog',
            field=models.TextField(),
        ),
    ]
