# Generated by Django 4.1.4 on 2023-01-17 03:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comentario_comentario_alter_post_campo_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='comentario',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
