# Generated by Django 4.1.4 on 2023-01-17 03:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comentario_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='campo_blog',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
