# Generated by Django 4.1.4 on 2023-01-17 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_campo_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categoria',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='fecha_blog',
            field=models.DateTimeField(),
        ),
    ]
