# Generated by Django 4.1.4 on 2023-01-23 00:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_categoria_alter_post_fecha_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='descripcion_corta',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='campo_blog',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
