# Generated by Django 4.1.4 on 2023-01-23 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_descripcion_corta_alter_post_campo_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
