# Generated by Django 4.1.4 on 2023-01-23 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_comentario_fecha_alter_post_fecha_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
