# Generated by Django 4.1.4 on 2023-01-23 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_comentario_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='descripcion_corta',
            field=models.TextField(null=True),
        ),
    ]
